// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1pEaM5hIeR355vQJYCiC8Dt-_IuUy2rQ',
    appId: '1:491849270239:android:15deac28837cfa0514fa6a',
    messagingSenderId: '491849270239',
    projectId: 'htn2024-d21be',
    storageBucket: 'htn2024-d21be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfKgP-R0ZmFoYNE11ID7LEu48mcw3p60k',
    appId: '1:491849270239:ios:7988fce648ed2b1b14fa6a',
    messagingSenderId: '491849270239',
    projectId: 'htn2024-d21be',
    storageBucket: 'htn2024-d21be.appspot.com',
    iosBundleId: 'com.example.hackTheNorth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfKgP-R0ZmFoYNE11ID7LEu48mcw3p60k',
    appId: '1:491849270239:ios:7988fce648ed2b1b14fa6a',
    messagingSenderId: '491849270239',
    projectId: 'htn2024-d21be',
    storageBucket: 'htn2024-d21be.appspot.com',
    iosBundleId: 'com.example.hackTheNorth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB__yrUnSom9OvQXdwb1pKcNxLQh_1kTdY',
    appId: '1:491849270239:web:0778b8469cd6ae0114fa6a',
    messagingSenderId: '491849270239',
    projectId: 'htn2024-d21be',
    authDomain: 'htn2024-d21be.firebaseapp.com',
    storageBucket: 'htn2024-d21be.appspot.com',
  );

}